branches:
  only:
  - master
image: Visual Studio 2019
environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- cmd: msbuild /t:restore
build:
  verbosity: normal
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
deploy:
- provider: Environment
  name: sil-lsdev nuget
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false